---
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${CLEARDB_DATABASE_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    initialization-mode: always
    platform: mysql
server:
  port: ${PORT}
  error:
    whitelabel:
      enabled: false
    path: /error
valorank:
  rankname:
    page-size: 10
---


